name: Build and Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup JFrog Fly
        uses: jfrog/fly-action@v1
        with:
          url: https://viktorfarcic.jfrog.io

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: viktorfarcic.jfrog.io/docker/jfrog-demo:${{ github.sha }}
